apply plugin: 'com.android.library'

group = 'com.hucentai.apollosecurity'
version = '1.0.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()

android {
  namespace "com.hucentai.apollosecurity"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
  lintOptions { abortOnError false }
}
