import { useMutation } from "@tanstack/react-query";
import * as Linking from "expo-linking";
import { useRouter } from "expo-router";
import X from "lucide-react-native/icons/x";
import React, { useEffect, useState } from "react";
import { Platform, Pressable, ScrollView, Switch, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { apiPost } from "@/src/api/client";
import { AlertPreviewSheet } from "@/src/components/AlertPreviewSheet";
import { Sheet } from "@/src/components/Sheet";
import { TimeStepper } from "@/src/components/TimeStepper";
import { Body, Button, Card, Pill, SectionTitle } from "@/src/components/ui";
import { PRIVACY_POLICY_SUMMARY } from "@/src/domain/privacy";
import type { PushStatus } from "@/src/push/notifications";
import { useApollo } from "@/src/store/ApolloContext";
import { fonts, makeStyles, radius, spacing, useTheme } from "@/src/theme";
import { minimiseApp } from "@/src/utils/minimise";
import { goBackOrHome } from "@/src/utils/navigation";
import { getHigginsAuto, setHigginsAuto, useHiggins } from "@/src/voice/higgins";

const PUSH_LABEL: Record<PushStatus, string> = { granted: "Allowed", denied: "Not allowed", undetermined: "Not decided", blocked: "Blocked in Settings", unsupported: "Not available here" };
const useStyles = makeStyles((c) => ({
  root: { flex: 1, backgroundColor: c.surface }, top: { paddingHorizontal: spacing.xl, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingBottom: spacing.md }, title: { fontFamily: fonts.displayBold, fontSize: 28, color: c.onSurface },
  close: { width: 48, height: 48, alignItems: "center", justifyContent: "center", borderRadius: radius.pill, backgroundColor: c.surfaceSecondary, borderWidth: 1, borderColor: c.border }, content: { paddingHorizontal: spacing.xl, gap: spacing.xl, paddingBottom: spacing.xl },
  row: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: spacing.md, paddingVertical: spacing.sm }, label: { fontFamily: fonts.textMedium, fontSize: 16, color: c.onSurface, flex: 1 }, mono: { fontFamily: fonts.textMedium, fontSize: 12, color: c.onSurfaceSecondary },
  trustRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: spacing.md, paddingVertical: spacing.sm, borderBottomWidth: 1, borderBottomColor: c.divider }, footer: { fontFamily: fonts.text, fontSize: 12, color: c.muted, textAlign: "center" },
}));

export default function SettingsScreen() {
  const s = useStyles(); const insets = useSafeAreaInsets(); const router = useRouter(); const { colors } = useTheme();
  const { deviceId, trust, revokeTrust, clearPatrol, pushStatus, pushRegistration, pushDetail, enablePush, quietHours, quietNow, setQuietHours, lowPower, setLowPower, showToast } = useApollo();
  const [higginsAuto, setHigginsAutoState] = useState(false); const [confirmClear, setConfirmClear] = useState(false); const [preview, setPreview] = useState(false);
  useEffect(() => { void getHigginsAuto().then(setHigginsAutoState); }, []);
  const higgins = useHiggins(deviceId);
  const testPush = useMutation({
    mutationFn: () => apiPost<{ deliveryId: string; state: string; failureCode: string | null }>("/push/test", "push_test", { device_id: deviceId }),
    onSuccess: (d) => showToast(d.state === "provider_accepted" ? "The alert service accepted the test. Check your notifications." : d.state === "outcome_unknown" ? "The alert service has not confirmed the test yet." : d.state === "failed" ? "The alert service could not send the test." : `Test alert ${d.state}.`, d.state === "failed" ? "barking" : "resting"),
    onError: () => showToast("Apollo could not send the test alert.", "barking"),
  });

  return <View style={s.root} testID="settings-screen">
    <View style={[s.top, { paddingTop: insets.top + spacing.md }]}><Text style={s.title} testID="settings-title">Settings</Text><Pressable testID="settings-close" accessibilityRole="button" accessibilityLabel="Close Settings" onPress={() => goBackOrHome(router)} style={s.close}><X size={22} color={colors.onSurface} /></Pressable></View>
    <ScrollView contentContainerStyle={[s.content, { paddingBottom: insets.bottom + spacing.xl }]} testID="settings-scroll">
      <View><SectionTitle>Privacy</SectionTitle><Card testID="settings-privacy">{PRIVACY_POLICY_SUMMARY.map((line) => <Body key={line} style={{ marginBottom: spacing.sm }}>• {line}</Body>)}<View style={s.row}><Text style={s.label}>Anonymous device reference</Text><Text style={s.mono} testID="settings-device-id">{deviceId ? `${deviceId.slice(0, 8)}…` : "—"}</Text></View><Button testID="settings-privacy-disclosure" variant="secondary" label="Read the privacy information" onPress={() => router.push("/privacy-disclosure")} /></Card></View>
      <View><SectionTitle>Share into Apollo</SectionTitle><Card style={{ gap: spacing.sm }} testID="settings-share"><Body>Use Share in Messages, Mail or your browser, then choose Apollo. Apollo waits for you to confirm before starting a check.</Body><Pill testID="settings-share-status" tone={Platform.OS === "web" ? "unknown" : "neutral"} label={Platform.OS === "web" ? "Available in the installed app" : "Available on this device"} /></Card></View>
      <View><SectionTitle>Security alerts</SectionTitle><Card style={{ gap: spacing.sm }} testID="settings-push"><View style={s.row}><Text style={s.label}>Allow important security alerts</Text><Pill tone={pushStatus === "granted" ? "resting" : pushStatus === "unsupported" ? "unknown" : "growling"} label={PUSH_LABEL[pushStatus]} testID="settings-push-status" /></View><Body>This permission lets Apollo show important warnings and family replies. It does not prove that a test alert was delivered.</Body>{pushStatus === "denied" || pushStatus === "undetermined" ? <Button testID="settings-push-enable" variant="secondary" label="Allow security alerts" onPress={() => void enablePush()} /> : null}{pushStatus === "blocked" ? <Button testID="settings-push-settings" variant="secondary" label="Open notification settings" onPress={() => void Linking.openSettings()} /> : null}{pushStatus === "granted" ? <><View style={s.row}><Text style={s.label}>Alert service</Text><Pill tone={pushRegistration === "registered" ? "resting" : "unknown"} label={pushRegistration === "registered" ? "Ready" : "Needs checking"} testID="settings-push-registration" /></View>{pushDetail ? <Body testID="settings-push-detail">{pushDetail}</Body> : null}{pushRegistration === "pending" || pushRegistration === "failed" ? <Button testID="settings-push-retry" variant="ghost" label="Try alert setup again" onPress={() => void enablePush()} /> : null}<Button testID="settings-push-test" variant="secondary" label={testPush.isPending ? "Sending…" : "Send a test alert"} onPress={() => testPush.mutate()} disabled={testPush.isPending || pushRegistration !== "registered"} /></> : null}<Button testID="settings-alert-preview" variant="ghost" label="Preview an alert" onPress={() => setPreview(true)} /></Card></View>
      <View><SectionTitle>Quiet hours</SectionTitle><Card style={{ gap: spacing.sm }} testID="settings-quiet"><View style={s.row}><Text style={s.label}>Silence non-urgent reminders at night</Text><Switch testID="settings-quiet-switch" value={quietHours.enabled} onValueChange={(value) => void setQuietHours({ ...quietHours, enabled: value })} trackColor={{ true: colors.resting, false: colors.borderStrong }} thumbColor={colors.onSurface} /></View><Body>Urgent threat warnings and family alerts can still appear.</Body>{quietHours.enabled ? <View style={{ flexDirection: "row", gap: spacing.md }}><TimeStepper testID="settings-quiet-start" label="From" minutes={quietHours.start_minutes} onChange={(minutes) => void setQuietHours({ ...quietHours, start_minutes: minutes })} /><TimeStepper testID="settings-quiet-end" label="Until" minutes={quietHours.end_minutes} onChange={(minutes) => void setQuietHours({ ...quietHours, end_minutes: minutes })} /></View> : null}{quietHours.enabled ? <Pill tone={quietNow ? "unknown" : "resting"} label={quietNow ? "Quiet hours are active" : "Quiet hours are not active now"} testID="settings-quiet-now" /> : null}</Card></View>
      <View><SectionTitle>Battery</SectionTitle><Card style={{ gap: spacing.sm }} testID="settings-battery"><View style={s.row}><Text style={s.label}>Battery saver</Text><Switch testID="settings-lowpower-switch" value={lowPower} onValueChange={(value) => void setLowPower(value)} trackColor={{ true: colors.resting, false: colors.borderStrong }} thumbColor={colors.onSurface} /></View><Body>Reduces animation and checks status less often while Apollo is open. It does not change the protection status shown in Gates.</Body><Button testID="settings-minimise" variant="secondary" label="Minimise Apollo" onPress={() => void minimiseApp(showToast)} /></Card></View>
      <View><SectionTitle>Family sharing</SectionTitle><Card style={{ gap: spacing.sm }} testID="settings-family-card"><Body>Choose a trusted family member who can receive the alerts you deliberately share.</Body><Button testID="settings-family" variant="secondary" label="Manage family sharing" onPress={() => router.push("/family")} /></Card></View>
      <View><SectionTitle>Trusted links ({trust.length})</SectionTitle><Card testID="settings-trust">{trust.length === 0 ? <Body>No links are trusted. Trust applies only to one exact link and never overrides a confirmed threat.</Body> : trust.map((entry) => <View key={entry.trust_id} style={s.trustRow} testID={`settings-trust-${entry.trust_id}`}><View style={{ flex: 1 }}><Text style={s.label}>{entry.indicator_host}</Text><Body>Exact link · {new Date(entry.created_at).toLocaleDateString()}</Body></View><Button testID={`settings-revoke-${entry.trust_id}`} variant="secondary" label="Remove trust" onPress={() => revokeTrust(entry)} /></View>)}</Card></View>
      <View><SectionTitle>Patrol history</SectionTitle><Card style={{ gap: spacing.md }} testID="settings-data"><Body>Patrol keeps plain summaries on this device. Technical saving details are in Support.</Body><Button testID="settings-clear-patrol" variant="secondary" label="Clear Patrol history" onPress={() => setConfirmClear(true)} /></Card></View>
      <View><SectionTitle>Higgins' voice</SectionTitle><Card style={{ gap: spacing.md }} testID="settings-higgins"><Body>Higgins can read an explanation aloud. Written guidance and actions remain available when audio is off.</Body><View style={s.row}><Text style={s.label}>Read urgent explanations aloud</Text><Switch testID="settings-higgins-auto" value={higginsAuto} onValueChange={(value) => { setHigginsAutoState(value); void setHigginsAuto(value); }} trackColor={{ true: colors.resting, false: colors.borderStrong }} thumbColor={colors.onSurface} /></View><Button testID="settings-higgins-sample" variant="secondary" label={higgins.busy ? "Preparing audio…" : higgins.speaking ? "Stop audio" : "Hear a sample"} onPress={() => void higgins.speak("Higgins here. I will explain what Apollo found and what you can do next.").catch(() => showToast("Audio isn't available right now.", "neutral"))} /></Card></View>
      <View><SectionTitle>Support</SectionTitle><Card style={{ gap: spacing.sm }} testID="settings-support"><Body>Find technical details, current service information and a manual protection check.</Body><Button testID="settings-open-support" variant="secondary" label="Open Support" onPress={() => router.push("/support")} /></Card></View>
      <View><SectionTitle>About</SectionTitle><Card style={{ gap: spacing.sm }} testID="settings-about"><Text style={s.label}>Apollo is a brand of Harmony Wellness Group.</Text><Body>Apollo performs supported checks and protection. Higgins explains findings and guides the next step.</Body></Card></View>
      <Text style={s.footer} testID="settings-footer">Apollo V1 · No account · No advertising tracking</Text>
    </ScrollView>
    <AlertPreviewSheet visible={preview} onClose={() => setPreview(false)} />
    <Sheet visible={confirmClear} onClose={() => setConfirmClear(false)} title="Clear Patrol history?" testID="clear-sheet"><Body>This hides Patrol items on this device and asks the service to hide synced summaries. Trusted links are kept.</Body><Button testID="clear-confirm" variant="danger" label="Clear history" onPress={() => { setConfirmClear(false); void clearPatrol(); }} /><Button testID="clear-cancel" variant="ghost" label="Keep history" onPress={() => setConfirmClear(false)} /></Sheet>
  </View>;
}