// Single maintained processing inventory; screen + Settings summaries must refer here.
export const PRIVACY_FLOWS = [
  { what: 'Purpose-limited security assessments', when: 'When you submit a message, email, screenshot, account alert, phone number or link', detail: 'Apollo combines on-device detection with Gemini context and supported reputation sources. Raw submitted content is not kept in Patrol, logs or analytics. Request-scoped copies close immediately after completion or failure and never later than 15 minutes.' },
  { what: 'Optional ongoing access', when: 'Only after you enable notification access or connect a mailbox', detail: 'Android notification checks and mailbox connections are opt-in. Disconnect or disable access to stop future checks. OAuth tokens and IMAP app passwords are encrypted while a mailbox remains connected.' },
  { what: 'Links you investigate', when: 'When you manually check or share a link, message or email', detail: 'Apollo receives a sanitised URL for the requested investigation. Credentials, fragments and secret query values are removed first. Reputation, safe webpage and domain-registration services receive only the URL or hostname needed for their check. Cached reputation uses a digest; expired rows are ignored, not treated as current evidence.' },
  { what: 'Minimal Patrol summaries and packet evidence', when: 'After checks and native observations; retried until acknowledged', detail: 'Apollo stores category, state, timestamps, opaque event IDs and website domain. Packet evidence adds mechanism, protocol, rule ID, port and observed action. No caller numbers, app/process attribution or raw message narratives. Clear Patrol currently hides server rows (soft deletion), not physical erasure. Pending uploads are shown in Patrol.' },
  { what: 'Device and notification settings', when: 'Setup, heartbeat, notification enablement and settings changes', detail: 'A server-issued random device ID, platform/app version, coarse UTC offset and quiet-hour preferences go to Apollo. Push delivery tokens go to the managed relay and Apple/Google delivery services. Disable notifications in Settings to stop notifications; this is not data erasure.' },
  { what: 'Ask Higgins and Hear Higgins', when: 'When you send a question, tap read-aloud, or explicitly enable automatic read-aloud', detail: 'Questions go to Google Gemini; do not paste private messages or secrets. Automatic event context is replaced with a generic summary. Text for speech goes to OpenAI. Apollo retains conversation history and cached speech; no automatic physical purge is currently guaranteed. Turning off read-aloud stops future automatic speech requests.' },
  { what: 'Optional family support', when: 'You pair, invite, share an incident, reply or explicitly send a note', detail: 'Chosen names, contact details, minimal alerts, weekly counts and replies go to Apollo and paired guardians. Invitations use an email delivery service; alerts use the push relay. Voice notes you explicitly send are stored in managed object storage and captioned by OpenAI Whisper. Family records/voice notes have no automatic purge guarantee. Remove a pairing to stop future sharing; it does not erase prior deliveries.' },
  { what: 'App reputation checks', when: 'You manually check an app', detail: 'The supplied app/developer names, source, permission labels and website hosts go to Apollo and optionally Gemini for explanation, not your full app inventory. Do not enter personal content in app-name fields.' },
  { what: 'Optional mailbox investigation', when: 'Only after you connect Gmail or an IMAP mailbox and start a scan or monitor', detail: 'Apollo uses read-only mailbox access to investigate supported messages. Gmail OAuth tokens and IMAP app passwords stay encrypted while connected. Disconnect removes Apollo’s stored connection; revoke provider access as an additional control. Raw message content is not copied into Patrol.' },
];
export const LOCAL_ONLY_CONTENT = ['Passwords, verification codes and sensitive URL tokens', 'Full messages, screenshots and files after their submitted assessment completes', 'Browsing history, precise location, IMEI, serial number and advertising ID'];