// Single maintained processing inventory; screen + Settings summaries must refer here.
export const PRIVACY_FLOWS = [
  { what: 'Local security checks', when: 'Messages, emails, account alerts, files and optional Android notification access', detail: 'Raw content stays on your phone. Automatic notification checks make no cloud request. Cloud OCR, page reading, inbox scanning, caller-number and breach-identifier lookups are disabled.' },
  { what: 'Website origins you check', when: 'When you manually check or share a link, message or email', detail: 'Apollo sends only scheme, host and port for reputation. Paths, queries, credentials and fragments are removed. Google Safe Browsing receives that origin; public DNS, redirect targets and RDAP registries see necessary hostname requests. Results are cached by digest (minutes); domain registration information is cached for 48 hours. Expired rows are ignored, not automatically erased.' },
  { what: 'Minimal Patrol summaries and packet evidence', when: 'After checks and native observations; retried until acknowledged', detail: 'Apollo stores category, state, timestamps, opaque event IDs and website domain. Packet evidence adds mechanism, protocol, rule ID, port and observed action. No caller numbers, app/process attribution or raw message narratives. Clear Patrol currently hides server rows (soft deletion), not physical erasure. Pending uploads are shown in Patrol.' },
  { what: 'Device and notification settings', when: 'Setup, heartbeat, notification enablement and settings changes', detail: 'A server-issued random device ID, platform/app version, coarse UTC offset and quiet-hour preferences go to Apollo. Push delivery tokens go to the managed relay and Apple/Google delivery services. Disable notifications in Settings to stop notifications; this is not data erasure.' },
  { what: 'Ask Higgins and Hear Higgins', when: 'When you send a question, tap read-aloud, or explicitly enable automatic read-aloud', detail: 'Questions go to Google Gemini; do not paste private messages or secrets. Automatic event context is replaced with a generic summary. Text for speech goes to OpenAI. Apollo retains conversation history and cached speech; no automatic physical purge is currently guaranteed. Turning off read-aloud stops future automatic speech requests.' },
  { what: 'Optional family support', when: 'You pair, invite, share an incident, reply or explicitly send a note', detail: 'Chosen names, contact details, minimal alerts, weekly counts and replies go to Apollo and paired guardians. Invitations use an email delivery service; alerts use the push relay. Voice notes you explicitly send are stored in managed object storage and captioned by OpenAI Whisper. Family records/voice notes have no automatic purge guarantee. Remove a pairing to stop future sharing; it does not erase prior deliveries.' },
  { what: 'App reputation checks', when: 'You manually check an app', detail: 'The supplied app/developer names, source, permission labels and website hosts go to Apollo and optionally Gemini for explanation, not your full app inventory. Do not enter personal content in app-name fields.' },
  { what: 'Legacy inbox connections', when: 'Previously connected installs only', detail: 'New connections and scans are disabled. Encrypted credentials from previous connections remain until you tap Disconnect on the Email screen. Disconnect removes Apollo’s stored connection; provider-side authorization can also be revoked in your provider settings.' },
];
export const LOCAL_ONLY_CONTENT = ['Messages, emails, contacts, screenshots and file bytes used in security checks', 'Automatically captured notification text and caller numbers', 'Browsing history, precise location, IMEI, serial number and advertising ID'];