// Recovery ("Stay With Me") kinds and steps — pure domain data shared by RecoveryFlow, the store and the Incident Timeline.

export type RecoveryKind = "clicked" | "password" | "code" | "money" | "info" | "app" | "card" | "download" | "called" | "remote" | "accessibility" | "profile" | "banking_during_access" | "mfa_approved" | "locked_out";
/** Recovery guidance ("Stay With Me"). First step doubles as the event's what_to_do. */
export const RECOVERY_STEPS: Record<RecoveryKind, string[]> = {
  mfa_approved: ["Open the service's official app, or type its address yourself, and sign out of every other device and session — now, if you would.", "Change the password straight away. Whoever triggered that prompt already knows it.", "Check the recovery email and phone are still yours; put them right if not.", "Decline every further approval prompt. Turn on number-matching or an authenticator app if it's offered.", "If this is a bank or payment account, do ring them on the number printed on your card."],
  locked_out: ["Use only the provider's official account-recovery page — type the address yourself or use their app. Never a link or number somebody sent you.", "Have your recovery email, phone and any backup codes to hand; the provider will verify you.", "Once you're back in: change the password, sign out all other sessions and restore your recovery details.", "Look for forwarding rules or newly linked apps the intruder may have left behind.", "If it's a bank or holds payment details, ring the bank on the number on your card."],
  remote: ["End the remote-access session this instant: turn off Wi‑Fi and mobile data, or restart the phone.", "Hang up on the caller, and don't ring the number back.", "Remove or disable the remote-access app and any permissions it was granted (Settings → Apps).", "Review the accounts you used while they were connected — change those passwords from a device they never touched.", "Decline any login or MFA prompts you didn't start yourself.", "If any banking took place during the session, ring your bank on the number on your card."],
  accessibility: ["Open Settings → Accessibility and switch the service off for that app.", "If it won't switch off or keeps returning, uninstall the app (Settings → Apps).", "Change any passwords you typed while it was on — from a different device if you're able.", "Keep an eye out for unexpected messages or login alerts."],
  profile: ["Open Settings → General → VPN & Device Management (iPhone) or Settings → Security (Android).", "Remove any profile, certificate or device-admin app you didn't deliberately install for work, or a VPN you chose yourself.", "Turn off any VPN you didn't set up.", "Restart the phone and confirm the profile has gone."],
  banking_during_access: ["Ring your bank now on the number on the back of your card and tell them someone had access to your phone.", "Ask them to check for unauthorised transfers and to reset your online banking access.", "Change your email password from another device — email is the key to everything else.", "Turn on or reset two-factor authentication, and decline any prompts you didn't start.", "Report it at ReportCyber (cyber.gov.au) and Scamwatch."],
  clicked: ["Do close the page. If you merely looked, you're almost certainly quite alright.", "Don't enter anything should it ask for details.", "Let Apollo check the link so it can be blocked."],
  password: ["Open the real service yourself — the official app or a typed address — and change that password now.", "If you use that password anywhere else, change it there as well.", "Sign out of other sessions if the service allows it.", "Decline any login or MFA prompts you didn't start."],
  code: ["Treat this as an account takeover in progress: open the real service now and change the password.", "Turn on or reset two-factor authentication.", "Check recent activity and contact the service using details you find yourself."],
  money: ["Contact your bank or payment provider immediately, using the number on your card or their official app.", "Ask them to stop or recall the payment — I'm afraid Apollo can't promise funds will return.", "Report it at ReportCyber (cyber.gov.au) and Scamwatch."],
  info: ["Note exactly what you shared (ID, card, address).", "For card details: ring your bank and cancel the card.", "For ID documents: contact IDCARE (idcare.org) — the support is free."],
  app: ["Don't open the app. Turn off Wi‑Fi and mobile data if a stranger is connected.", "Uninstall the app from your phone's settings.", "Change your banking and email passwords from a different device if you're able."],
  card: ["Ring your bank now, using the number on the back of your card, and ask them to block it.", "Check recent transactions and dispute anything you don't recognise.", "Don't reply to any follow-up messages or calls about this — they may well be the same people."],
  download: ["Don't open the file. Delete it from your Downloads.", "If it was an app installer (APK or profile), remove it from Settings as well.", "Run your phone's built-in security check (Google Play Protect, or an iOS software update)."],
  called: ["Hang up if you're still on the call, and don't ring the number back.", "If you shared any details or installed anything, follow those recovery steps too.", "Block the number, and report the call at Scamwatch."],
};
