/* global __dirname */
const { withEntitlementsPlist, withInfoPlist, withPodfile, withXcodeProject } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const TARGET = "ApolloFamilyAssistBroadcast";
const BUNDLE = "app.apollo.hwg.familyassistbroadcast";
const GROUP = "group.app.apollo.hwg.apollo";
const POD_MARKER = "# @generated by withApolloFamilyAssist";

function writeTargetFiles(root) {
  const source = path.join(__dirname, "..", "ios", "Broadcast");
  const target = path.join(root, TARGET);
  fs.mkdirSync(target, { recursive: true });
  for (const name of ["SampleHandler.swift", "Info.plist", `${TARGET}.entitlements`]) fs.copyFileSync(path.join(source, name), path.join(target, name));
}

function ensureTarget(project, root) {
  if (project.pbxTargetByName(TARGET)) return;
  writeTargetFiles(root);
  const target = project.addTarget(TARGET, "app_extension", TARGET, BUNDLE);
  const group = project.addPbxGroup(["SampleHandler.swift", "Info.plist", `${TARGET}.entitlements`], TARGET, TARGET);
  project.addToPbxGroup(group.uuid, project.getFirstProject().firstProject.mainGroup);
  project.addBuildPhase(["SampleHandler.swift"], "PBXSourcesBuildPhase", "Sources", target.uuid);
  const section = project.pbxXCBuildConfigurationSection();
  for (const key in section) {
    const settings = section[key].buildSettings;
    if (!settings || settings.PRODUCT_NAME !== `"${TARGET}"`) continue;
    settings.INFOPLIST_FILE = `"${TARGET}/Info.plist"`;
    settings.CODE_SIGN_ENTITLEMENTS = `"${TARGET}/${TARGET}.entitlements"`;
    settings.IPHONEOS_DEPLOYMENT_TARGET = "16.4";
    settings.APPLICATION_EXTENSION_API_ONLY = "YES";
    settings.SKIP_INSTALL = "YES";
    settings.TARGETED_DEVICE_FAMILY = '"1,2"';
    settings.SWIFT_VERSION = "5.0";
  }
}

module.exports = function withApolloFamilyAssist(config) {
  config = withInfoPlist(config, (value) => { value.modResults.FamilyAssistAppGroup = GROUP; return value; });
  config = withEntitlementsPlist(config, (value) => {
    const key = "com.apple.security.application-groups";
    value.modResults[key] = [...new Set([...(value.modResults[key] || []), GROUP])];
    return value;
  });
  config = withPodfile(config, (value) => {
    if (!value.modResults.contents.includes(POD_MARKER)) {
      value.modResults.contents += `\n${POD_MARKER}\ntarget '${TARGET}' do\n  pod 'JitsiWebRTC', '~> 124.0.0'\nend\n`;
    }
    return value;
  });
  return withXcodeProject(config, (value) => { ensureTarget(value.modResults, value.modRequest.platformProjectRoot); return value; });
};