import { useRouter } from "expo-router";
import Search from "lucide-react-native/icons/search";
import React, { useEffect, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, ScrollView, Text, TextInput, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { ChildScreenHeader } from "@/src/components/ChildScreenHeader";
import { Body, Button, Card } from "@/src/components/ui";
import { learningArticles, type LearningArticleSummary } from "@/src/higgins/hubClient";
import { fonts, makeStyles, radius, spacing, useTheme } from "@/src/theme";

const useStyles = makeStyles((c) => ({ root: { flex: 1, backgroundColor: c.surface }, list: { paddingHorizontal: spacing.xl, gap: spacing.md }, title: { fontFamily: fonts.displayBold, fontSize: 18, color: c.onSurface }, search: { flexDirection: "row", alignItems: "center", gap: spacing.sm, minHeight: 52, borderWidth: 1, borderColor: c.border, borderRadius: radius.md, paddingHorizontal: spacing.md, backgroundColor: c.surfaceSecondary }, input: { flex: 1, fontFamily: fonts.text, fontSize: 16, color: c.onSurface }, chips: { gap: spacing.sm }, chip: { minHeight: 44, justifyContent: "center", paddingHorizontal: spacing.lg, borderRadius: radius.pill, borderWidth: 1, borderColor: c.border, backgroundColor: c.surfaceSecondary }, chipText: { fontFamily: fonts.textMedium, color: c.onSurface } }));
export default function HigginsLearningScreen() {
  const s = useStyles(); const { colors } = useTheme(); const router = useRouter(); const insets = useSafeAreaInsets();
  const [items, setItems] = useState<LearningArticleSummary[]>([]); const [groups, setGroups] = useState<string[]>([]); const [group, setGroup] = useState(""); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  const load = () => { setLoading(true); setError(false); void learningArticles(group || undefined, search || undefined).then((result) => { setItems(result.items); setGroups(result.groups); }).catch(() => setError(true)).finally(() => setLoading(false)); };
  useEffect(load, [group]); // eslint-disable-line react-hooks/exhaustive-deps
  return <View style={s.root} testID="higgins-learning-screen"><ChildScreenHeader title="Learn with Higgins" testID="higgins-learning-header" /><FlatList testID="higgins-learning-list" data={items} keyExtractor={(item) => item.slug} contentContainerStyle={[s.list, { paddingBottom: insets.bottom + spacing.xl }]} ListHeaderComponent={<View style={{ gap: spacing.md }}><Card testID="higgins-learning-intro"><Body>Practical scam-safety guidance kept and reviewed by Apollo. The app fetches each article when you open it and does not store the library in the consumer bundle.</Body></Card><View style={s.search}><Search size={20} color={colors.muted} /><TextInput testID="higgins-learning-search" value={search} onChangeText={setSearch} onSubmitEditing={load} placeholder="Search learning topics" placeholderTextColor={colors.muted} style={s.input} returnKeyType="search" /><Button testID="higgins-learning-search-button" variant="ghost" label="Search" onPress={load} /></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips} testID="higgins-learning-groups"><Pressable testID="higgins-learning-group-all" onPress={() => setGroup("")} style={s.chip}><Text style={s.chipText}>All topics</Text></Pressable>{groups.map((item) => <Pressable key={item} testID={`higgins-learning-group-${item.toLowerCase().replace(/[^a-z]+/g, "-")}`} onPress={() => setGroup(item)} style={s.chip}><Text style={s.chipText}>{item}</Text></Pressable>)}</ScrollView></View>} renderItem={({ item }) => <Pressable testID={`higgins-learning-article-${item.slug}`} accessibilityRole="button" accessibilityLabel={item.title} onPress={() => router.push({ pathname: "/higgins/learning/[slug]", params: { slug: item.slug } })}><Card style={{ gap: spacing.sm }}><Text style={s.title}>{item.title}</Text><Body>{item.summary}</Body><Body>{item.group} · {item.sourceNames.join(" and ")}</Body></Card></Pressable>} ListEmptyComponent={loading ? <ActivityIndicator testID="higgins-learning-loading" color={colors.brand} /> : error ? <Card testID="higgins-learning-error"><Body>Learning could not be loaded. Nothing has been cached in the app.</Body><Button testID="higgins-learning-retry" label="Try again" onPress={load} /></Card> : <Card testID="higgins-learning-empty"><Body>No published articles match this view.</Body></Card>} /></View>;
}