import { useRouter } from "expo-router";
import Search from "lucide-react-native/icons/search";
import React, { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, ScrollView, Text, TextInput, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { ChildScreenHeader } from "@/src/components/ChildScreenHeader";
import { Body, Button, Card } from "@/src/components/ui";
import { learningArticles, type LearningArticleSummary } from "@/src/higgins/hubClient";
import { fonts, makeStyles, radius, spacing, useTheme } from "@/src/theme";

const useStyles = makeStyles((c) => ({ root: { flex: 1, backgroundColor: c.surface }, list: { paddingHorizontal: spacing.xl, gap: spacing.md }, title: { fontFamily: fonts.displayBold, fontSize: 18, color: c.onSurface }, search: { flexDirection: "row", alignItems: "center", gap: spacing.sm, minHeight: 52, borderWidth: 1, borderColor: c.border, borderRadius: radius.md, paddingHorizontal: spacing.md, backgroundColor: c.surfaceSecondary }, input: { flex: 1, fontFamily: fonts.text, fontSize: 16, color: c.onSurface }, filterLabel: { fontFamily: fonts.textMedium, color: c.muted }, chips: { gap: spacing.sm }, chip: { minHeight: 44, justifyContent: "center", paddingHorizontal: spacing.lg, borderRadius: radius.pill, borderWidth: 1, borderColor: c.border, backgroundColor: c.surfaceSecondary }, chipText: { fontFamily: fonts.textMedium, color: c.onSurface } }));

function FilterRow({ label, id, items, value, onChange, styles }: { label: string; id: string; items: string[]; value: string; onChange: (value: string) => void; styles: ReturnType<typeof useStyles> }) {
  if (!items.length) return null;
  return <View style={{ gap: spacing.xs }}><Text style={styles.filterLabel}>{label}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips} testID={`higgins-learning-filter-${id}`}><Pressable testID={`higgins-learning-${id}-all`} accessibilityState={{ selected: !value }} onPress={() => onChange("")} style={styles.chip}><Text style={styles.chipText}>All</Text></Pressable>{items.map((item) => <Pressable key={item} testID={`higgins-learning-${id}-${item.toLowerCase().replace(/[^a-z]+/g, "-")}`} accessibilityState={{ selected: value === item }} onPress={() => onChange(item)} style={styles.chip}><Text style={styles.chipText}>{item.replaceAll("_", " ")}</Text></Pressable>)}</ScrollView></View>;
}

export default function HigginsLearningScreen() {
  const s = useStyles(); const { colors } = useTheme(); const router = useRouter(); const insets = useSafeAreaInsets();
  const [items, setItems] = useState<LearningArticleSummary[]>([]); const [filters, setFilters] = useState<Record<string, string[]>>({});
  const [category, setCategory] = useState(""); const [audience, setAudience] = useState(""); const [riskContext, setRiskContext] = useState(""); const [contentType, setContentType] = useState("");
  const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  const load = useCallback(() => { setLoading(true); setError(false); void learningArticles({ category: category || undefined, audience: audience || undefined, riskContext: riskContext || undefined, contentType: contentType || undefined, search: search || undefined, language: "en-AU" }).then((result) => { setItems(result.items); setFilters(result.filters); }).catch(() => setError(true)).finally(() => setLoading(false)); }, [audience, category, contentType, riskContext, search]);
  useEffect(() => { load(); }, [audience, category, contentType, riskContext]); // eslint-disable-line react-hooks/exhaustive-deps
  const header = <View style={{ gap: spacing.md }}><Card testID="higgins-learning-intro"><Body>Practical Australian scam-safety guidance published and reviewed by Apollo. Articles stay on the backend and include dated official sources.</Body></Card><View style={s.search}><Search size={20} color={colors.muted} /><TextInput testID="higgins-learning-search" value={search} onChangeText={setSearch} onSubmitEditing={load} placeholder="Search learning topics" placeholderTextColor={colors.muted} style={s.input} returnKeyType="search" /><Button testID="higgins-learning-search-button" variant="ghost" label="Search" onPress={load} /></View><FilterRow label="Topic" id="category" items={filters.category ?? []} value={category} onChange={setCategory} styles={s} /><FilterRow label="Audience" id="audience" items={filters.audience ?? []} value={audience} onChange={setAudience} styles={s} /><FilterRow label="Risk context" id="risk" items={filters.risk_context ?? []} value={riskContext} onChange={setRiskContext} styles={s} /><FilterRow label="Article type" id="type" items={filters.content_type ?? []} value={contentType} onChange={setContentType} styles={s} /></View>;
  return <View style={s.root} testID="higgins-learning-screen"><ChildScreenHeader title="Learn with Higgins" testID="higgins-learning-header" /><FlatList testID="higgins-learning-list" data={items} keyExtractor={(item) => item.slug} contentContainerStyle={[s.list, { paddingBottom: insets.bottom + spacing.xl }]} ListHeaderComponent={header} renderItem={({ item }) => <Pressable testID={`higgins-learning-article-${item.slug}`} accessibilityRole="button" accessibilityLabel={item.title} onPress={() => router.push({ pathname: "/higgins/learning/[slug]", params: { slug: item.slug } })}><Card style={{ gap: spacing.sm }}><Text style={s.title}>{item.title}</Text><Body>{item.summary}</Body><Body>{item.category} · {item.contentType.replace("_", " ")} · {item.sourceNames.join(" and ")}</Body>{item.reviewStatus === "due" ? <Body>Review due — check the dated official sources.</Body> : null}</Card></Pressable>} ListEmptyComponent={loading ? <ActivityIndicator testID="higgins-learning-loading" color={colors.brand} /> : error ? <Card testID="higgins-learning-error"><Body>Learning could not be loaded. Nothing has been cached in the app.</Body><Button testID="higgins-learning-retry" label="Try again" onPress={load} /></Card> : <Card testID="higgins-learning-empty"><Body>No published articles match this view.</Body></Card>} /></View>;
}